### ISSUE TITLE
在Android 14上存在兼容性问题。

### ISSUE THREAD

**Issue by appdev** [DFFXT/SkinSwitch#1]
在Android 14 上 弹窗 diaolog popwindow。切换深浅色后，再次打开，还是切换之前的颜色。Android 14 一下没有发现这个问题。

**Comment by DFFXT** [comment]
该项目未在Android 14上进行实际测试，既然在Android 14上存在一些问题，那计划在下个版本中进行相关问题的修复，感谢您提出的问题。该问题计划在24号左右进行尝试修复。

**Comment by DFFXT** [comment]
master分支新增了对dialog、popupWindow的换肤测试，在Android 14模拟器上，结果为对图片、颜色，能正常换肤。能描述下你这边是如何使用的么，是否使用的是外置皮肤包、dialog中哪种资源（color？drawable？）没有被换肤。

同时，如果是通过切换系统中暗色模式的开关，会导致应用activity重建，需在AndroidManifest中添加android:configChanges="uiMode"配置，同时activity或者fragment中需重写

override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        // 对接系统白天黑夜模式
        if (newConfig.isNight() != SkinManager.isNightMode()) {
            SkinManager.applyThemeNight(newConfig.isNight())
        }
    }

**Comment by appdev** [comment]
没有使用外置皮肤包，但是使用了自定义View。对于自定义的属性，使用 `SkinManager.addAttributeCollection（XXX) ` 
在切换深浅色后是能立即换肤的，但是再次打开不行。

https://github.com/DFFXT/SkinSwitch/assets/9107717/69588290-7dfb-45a0-9d68-84f145464deb

**Comment by DFFXT** [comment]
通过视频分析，可能有两个原因
1. 自定义view换肤的BaseViewApply.apply方法没有在View创建时调用
2. apply方法调用了，但是BaseViewApply.apply 参数中的IResourceProvider对象提供了错误的资源

原因1确认方式：
    `SkinManager.addAttributeCollection（XXX) `执行器中添加日志，看dialog重新创建时是否执行了apply方法

原因2确认方式：
     当dialog换肤失败时，退出activity，再重新进入activity，看页面和dialog是否正常；更准确的方式是在apply方法中log输出对应的颜色值



 master分支中提交了dialog自定义属性的换肤测试，在模拟器14上测试无问题（也有可能模拟器测试不出来）视频超过10M，就不上传了。
推荐拉取master分支直接跑试试
也可以你那边提供个demo，我这边直接测试。

**Comment by appdev** [comment]
今天在其他界面测试了一下，发现它大部分情况下正常，偶尔异常。异常时报错：

```
  java.lang.NoSuchFieldException: No field mResId in class Landroid/content/res/Resources$ThemeKey; (declaration of 'android.content.res.Resources$ThemeKey' appears in /system/framework/framework.jar)
11:51:06.423  W  	at java.lang.Class.getDeclaredField(Native Method)
11:51:06.424  W  	at com.skin.skincore.reflex.SkinUtilKt.getResourcesKey(SkinUtil.kt:168)
11:51:06.424  W  	at com.skin.skincore.plug.SkinUtilKt.updateResource(SkinUtil.kt:48)
11:51:06.424  W  	at com.skin.skincore.loader.ContextLoader.switchTheme(ContextLoader.kt:88)
11:51:06.424  W  	at com.skin.skincore.loader.ContextLoader.<init>(ContextLoader.kt:74)
11:51:06.424  W  	at com.skin.skincore.SkinManager.makeContextSkinAble(SkinManager.kt:80)
11:51:06.424  W  	at com.skin.skincore.ActivitiesCallback.onActivityCreated(ActivitiesCallback.kt:19)
11:51:06.424  W  	at android.app.Application.dispatchActivityCreated(Application.java:368)
11:51:06.424  W  	at android.app.Activity.dispatchActivityCreated(Activity.java:1436)
11:51:06.424  W  	at android.app.Activity.onCreate(Activity.java:1736)
11:51:06.424  W  	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:86)
11:51:06.424  W  	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:314)
11:51:06.424  W  	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
11:51:06.424  W  	at android.app.Activity.performCreate(Activity.java:8760)
11:51:06.424  W  	at android.app.Activity.performCreate(Activity.java:8738)
11:51:06.424  W  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
11:51:06.424  W  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3913)
11:51:06.424  W  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4110)
11:51:06.424  W  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
11:51:06.424  W  	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
11:51:06.424  W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
11:51:06.424  W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
11:51:06.424  W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2537)
11:51:06.424  W  	at android.os.Handler.dispatchMessage(Handler.java:106)
11:51:06.424  W  	at android.os.Looper.loopOnce(Looper.java:205)
11:51:06.424  W  	at android.os.Looper.loop(Looper.java:294)
11:51:06.424  W  	at android.app.ActivityThread.main(ActivityThread.java:8470)
11:51:06.424  W  	at java.lang.reflect.Method.invoke(Native Method)
11:51:06.424  W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11:51:06.424  W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

不知道这个有没有影响

**Comment by DFFXT** [comment]
该问题不影响换肤，而且这个异常是当API>28时每次进入activity时均会报异常。
偶现问题的话应该是内部稳定性问题。你这边是跟随的系统模式，而且不会加载外部皮肤包。
可以试试最新：` implementation 'com.github.DFFXT.SkinSwitch:SkinCore:0.21.8' ` 版本

同时在SkinManger.init之前执行：
   ```
 AssetLoaderManager.setAssetFactory(object : IAssetFactory {
        override fun createAsset(context: Context, skinPathProvider: ISkinPathProvider): IAsset {
            return object : Asset(context, skinPathProvider) {
                override fun getResource(): Resources {
                    val resource = context.resources
                    // 使用系统默认Resource对象
                    if (resource is MergeResource) {
                        return resource.default
                    }
                    return super.getResource()
                }
            }
        }
    })
```
之前视频的现象和没有提供正确的白天黑夜模式的Resource对象一致

**Comment by appdev** [comment]
> 该问题不影响换肤，而且这个异常是当API>28时每次进入activity时均会报异常。 偶现问题的话应该是内部稳定性问题。你这边是跟随的系统模式，而且不会加载外部皮肤包。 可以试试最新：`implementation 'com.github.DFFXT.SkinSwitch:SkinCore:0.21.8'` 版本
> 
> 同时在SkinManger.init之前执行：
> 
> ```
> AssetLoaderManager.setAssetFactory(object : IAssetFactory {
>      override fun createAsset(context: Context, skinPathProvider: ISkinPathProvider): IAsset {
>          return object : Asset(context, skinPathProvider) {
>              override fun getResource(): Resources {
>                  val resource = context.resources
>                  // 使用系统默认Resource对象
>                  if (resource is MergeResource) {
>                      return resource.default
>                  }
>                  return super.getResource()
>              }
>          }
>      }
>  })
> ```
> 
> 之前视频的现象和没有提供正确的白天黑夜模式的Resource对象一致

好的。感谢我晚上试试

**Comment by appdev** [comment]
测试了一下，还是有点问题。可能不是框架的问题，我自己排查一下。感谢
